name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Build ESPHome Firmware
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - id: esphome-build
        name: ESPHome Builder
        uses: esphome/build-action@v1.0.1
        with:
          yaml_file: ./esphome/location-clock.yaml
          
      - name: Upload Firmware
        uses: actions/upload-artifact@master
        with:
          name: firmware
          path: ${{ steps.esphome-build.outputs.name }}
          
  deploy:
    name: Deploy new firmware to GitHub Pages
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@master
        with:
          name: firmware
          path: ./static/firmware
      
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.6
        with:
          branch: gh-pages
          folder: static